project:
  type: website
  output-dir: docs

website:
  title: "The Defence Economist"
  navbar:
    right:
      - about.qmd
      - text: "Knowledge"
        href: https://defenceeconomist.shinyapps.io/knowledgebase
      - icon: github
        href: https://github.com/defenceeconomist
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

